Fixed typos
lektor/lektor-website pull request #374
Opened 2023-05-22 09:56 UTC by 3kori

I hope this PR is welcomed. I have been practicing git commands and this repo has been really helpful. Thank you.

2023-05-22 22:16 UTC, dairiki requested changes
@3kori The PR is most welcomed. Thank you!

I did, however, notice a couple of misspellings in your corrections of previous misspellings.

2023-05-22 22:16 UTC, dairiki commented on content/docs/project/file/contents.lr
> +Lektor does some basic attachment type detection based on file extension. This is what powers the `this.attachements.images` and `this.attachments.videos` attributes for instance. If the built-in map
Should be `this.attachments.images`

2023-05-23 00:08 UTC, 3kori commented
I am sorry for making a mistake.

2023-05-23 00:24 UTC, merged

2023-05-23 00:25 UTC, dairiki commented
@3kori No problem!  Thank you for fixing all the typos you've found!